name: CI/CD

on:
    push:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Code Checkout
            - name: Checkout code
              uses: actions/checkout@v4

            # Docker Hub Login

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            # Build and Push Backend Image

            - name: Build Images
              run: docker compose build
              
            - name: Push images
              run: docker compose push  